import type { PackageGuardPolicy } from "./types";

export const PACKAGE_GUARD_PRESETS: PackageGuardPolicy[] = [
  {
    schemaVersion: 1,
    id: "strict-submission-review",
    name: "Strict Submission Review",
    description: "A conservative Kukureku package gate. This is not an official filing or regulatory standard.",
    minDocuments: 1,
    maxDocuments: null,
    maxTotalBytes: null,
    maxFileBytes: null,
    exactDuplicates: "warn",
    commonMetadata: "fail",
    interactiveForms: "fail",
    xfa: "fail",
    sensitivePatterns: "warn",
    noSelectableText: "warn",
    mixedPageSizes: "warn",
    rotatedPages: "ignore",
    customCropBoxes: "warn",
    graphIntegrity: "fail",
    requiredFilenameTokens: [],
  },
  {
    schemaVersion: 1,
    id: "share-review",
    name: "Share Review",
    description: "Reviews common privacy and structure risks before a package is shared. It does not certify that a package is safe.",
    minDocuments: 1,
    maxDocuments: null,
    maxTotalBytes: null,
    maxFileBytes: null,
    exactDuplicates: "warn",
    commonMetadata: "warn",
    interactiveForms: "warn",
    xfa: "fail",
    sensitivePatterns: "warn",
    noSelectableText: "warn",
    mixedPageSizes: "ignore",
    rotatedPages: "ignore",
    customCropBoxes: "ignore",
    graphIntegrity: "fail",
    requiredFilenameTokens: [],
  },
  {
    schemaVersion: 1,
    id: "integrity-only",
    name: "Integrity Gate",
    description: "Checks package readability, graph provenance, exact duplicates, and user-defined package limits without content-policy assumptions.",
    minDocuments: 1,
    maxDocuments: null,
    maxTotalBytes: null,
    maxFileBytes: null,
    exactDuplicates: "warn",
    commonMetadata: "ignore",
    interactiveForms: "ignore",
    xfa: "warn",
    sensitivePatterns: "ignore",
    noSelectableText: "ignore",
    mixedPageSizes: "ignore",
    rotatedPages: "ignore",
    customCropBoxes: "ignore",
    graphIntegrity: "fail",
    requiredFilenameTokens: [],
  },
];

export function getPackageGuardPreset(id: string) {
  return PACKAGE_GUARD_PRESETS.find((policy) => policy.id === id) ?? PACKAGE_GUARD_PRESETS[0];
}